### ISSUE TITLE
why the method  "isEmpty"   always return false

### ISSUE THREAD

**Issue by 2865724220** [WangShayne/vue-signature#10]

**Comment by WangShayne** [comment]
Unable to reproduce issue, Could you provide the demo please?

**Comment by 2865724220** [comment]
e，，demo may be can not provide, the situation is  checkout the canvas is empty or not when I use the save method,  and it always rerurn false.

**Comment by WangShayne** [comment]
sorry,我的锅.试一下1.8.0

**Comment by 2865724220** [comment]
哦，我其实用_this.$refs.signature.sig._lastVelocity这个值也能判断了，不过还是谢谢哦

**Comment by Wolrab1** [comment]
Using the lastVelocity isn't accurate because when the signature is finished with a . then the velocity = 0.

To get around this bug I would use the this.$refs.signature.sig._data.length value as this counts the number of strokes in the signature.
