### ISSUE TITLE
Duplicate method issue

### ISSUE THREAD

**Issue by Gaaab** [WangShayne/vue-signature#17]
https://github.com/WangShayne/vue-signature/blob/7f64e4144f9f40a818dc08a239f06965429d58a3/src/lib/vue-signature.vue#L131

**Comment by WangShayne** [comment]
sorry,my fault. fromDataURL

**Comment by Gaaab** [comment]
Still duplicated 😄 

https://github.com/WangShayne/vue-signature/blob/70be9aaa4c9ad44e1adc3be579561470f888a228/src/lib/vue-signature.vue#L131

https://github.com/WangShayne/vue-signature/blob/70be9aaa4c9ad44e1adc3be579561470f888a228/src/lib/vue-signature.vue#L84

**Comment by WangShayne** [comment]
omg, fromDataURL  already has it.But I forgot to write it on readme.
