### ISSUE TITLE
Add default watermark

### ISSUE THREAD

**Issue by drew-royster** [WangShayne/vue-signature#18]
I love this library and am using it for a legal document. To cover all bases I would like to add a default watermark to the signature box. I have tried adding the watermark on the `created` and `mounted` hooks, but it appears to be ignoring those. Would you mind add a default watermark option? A workaround would also be greatly appreciated!

**Comment by WangShayne** [comment]
Sorry, for replying for late.
you can set default waterMark now. Please check readme

**Comment by ChanRing** [comment]
how to remove waterMark ?

**Comment by WangShayne** [comment]
@ChanRing No such function is provided, you can try "undo"
