### ISSUE TITLE
fromDataURL is not a function

### ISSUE THREAD

**Issue by Gaaab** [WangShayne/vue-signature#19]
Hi! I am here again  😄 

![image](https://user-images.githubusercontent.com/7161331/44913725-c649ef80-ad60-11e8-9054-7b9eb9060d7c.png)

⚠️ 
https://github.com/WangShayne/vue-signature/blob/04b786d5c753e31164b80abd882d01b0aa43d748/src/lib/vue-signature.vue#L86

Reference 🔗 
https://github.com/szimek/signature_pad#api

**Comment by WangShayne** [comment]
hello, I cannot debug with your issue reporting.
Could you provide the minimum reproduction repo please?

**Comment by Gaaab** [comment]
Hi! seems I cannot do a pull request might as well create a public repo for this request

Here is the demo. Thanks.
https://github.com/Gaaab/vue-signature-demo/tree/request/from-data-url-is-not-a-function

**Comment by Gaaab** [comment]
Regarding the tech I am using

NodeJS 8.11.3
VueCli 3.0.0-rc.5

**Comment by WangShayne** [comment]
Hi,I try this repo. but I could not reproduce it

![PzdJpQ.gif](https://s1.ax1x.com/2018/09/03/PzdJpQ.gif)

**Comment by Gaaab** [comment]
Hmm... weird I tried re installing the package and it seems to be working. 🤔

Alright thanks for your effort you may close this issue.

**Comment by WangShayne** [comment]
okay

**Comment by DeepakAryal** [comment]
Hi i am getting this issue. i am using latest version 2.4.*

any help please?

**Comment by exemplari** [comment]
I had this issue when
1. Using multiple signature panels rendered under v-if
2. I solved it by setting a timeout :,( 
v-if removes elements from dom and they must re-render , vue-signature does not have an event to wait for and thus "sig.fromDataURL is not a function"
i previously was render with v-show, but had problems with that, probably related to https://github.com/neighborhood999/vue-signature-pad/issues/81

**Comment by WangShayne** [comment]
#28
