### ISSUE TITLE
Not working until the inspect element is used

### ISSUE THREAD

**Issue by rafi73** [WangShayne/vue-signature#21]
Hello Wang,
Thanks for the great plugin! I tried to use the plugin in my current application but I'm little confused. I cant use the plugin until I use the `inspect` from chrome/firefox/edge browser menu. I checked the integration several times and seems doing in the proper way.

I'm attaching 2 pictures. 
1.  Not working 
2. Working when I open the inspect mode 
![notworking-sig](https://user-images.githubusercontent.com/9848528/46257889-b444a380-c4fc-11e8-9aa1-cc647b568ac8.PNG)
![working-sig](https://user-images.githubusercontent.com/9848528/46257890-b4dd3a00-c4fc-11e8-95ab-a2c7dd06e459.PNG)

**Comment by WangShayne** [comment]
You may can't use it in a pop-up box

**Comment by abondarenko** [comment]
Are there any possibilities to have working solution inside a vue dialog?

**Comment by egeersoz** [comment]
What do you mean by "lazy"?

**Comment by abondarenko** [comment]
We use vuetify and v-dialog component.
https://vuetifyjs.com/en/components/dialogs
In this case with option "lasy" it works and otherwise.
