### ISSUE TITLE
fromDataURL is not a function

### ISSUE THREAD

**Issue by DeepakAryal** [WangShayne/vue-signature#28]
Hi i am getting this issue. i am using latest version 2.4.*

it works when i create the signature. but when i need to display the created(already saved) signature after refresh the page then i got this issue.

Is there different way to display already saved signature in signature pad?

what i am doing now is:
this.$refs.signature.fromDataURL('dataurl')

**Comment by WangShayne** [comment]
Because the $ref itself is created as a result of rendering, you cannot access them during the initial rendering, they do not exist yet.
so you can try
```
this.$nextTick(()=>{
    this.$refs.signature.fromDataURL(url)
})
```

**Comment by WangShayne** [comment]
sorry , it is my fault. now you can try give a defaultUrl
