### ISSUE TITLE
移动端横屏处理

### ISSUE THREAD

**Issue by xikong1995** [WangShayne/vue-signature#29]
如果在移动端想横屏展示，旋转后，屏幕的操作和canvas字迹显示就反了。请问什么相关的支持吗？或者好的处理方式

**Comment by WangShayne** [comment]
解决了?

**Comment by xikong1995** [comment]
转化了一下思路，就让它竖屏，最后把图片旋转一下，这样就横屏了。

**Comment by cxinde** [comment]
> 转化了一下思路，就让它竖屏，最后把图片旋转一下，这样就横屏了。

大兄弟，怎么旋转图片啊？
