### ISSUE TITLE
 Loading signature pad in a component no longer works.

### ISSUE THREAD

**Issue by marcelomaia** [WangShayne/vue-signature#35]
Seems to be the same, since bot libs depends on the same project.

https://github.com/neighborhood999/vue-signature-pad/issues/254

`
import vueSignature from "vue-signature"; 

components: { vueSignature },
`

**Comment by WangShayne** [comment]
try 2.4.6 please, it should work now

**Comment by jnardone** [comment]
This is still broken for us in 2.4.6

**Comment by WangShayne** [comment]
@jnardone try direct import
```vue
import vueSignarture from "vue-signature"
export default {
	name: "app",
	components:{
		vueSignarture
	},
```
