### ISSUE TITLE
Update to babel-env

### ISSUE THREAD

**Issue by matrunchyk** [WangShayne/vue-signature#38]
Hi! Thank you for your work!!!

How much time will take to upgrade to babel-env?
Now I got this message each time I install the package on a fresh vue-project:
> npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!

**Comment by WangShayne** [comment]
Update complete, thank you!
