### ISSUE TITLE
Test with Phantomjs produces SyntaxError: Unexpected token 'const'

### ISSUE THREAD

**Issue by danielgranat** [WangShayne/vue-signature#4]
Hi, Trying to run tests using vue-signature I get the following error:
SyntaxError: Unexpected token 'const'

Looking at the dist/vue-signature.js I see it indeed contains 'const'.
Running 'npm build' myself, with node 6.11.2, I get the transpiled file compatible phantomjs.

Is this something you can (and want to) make sure that bubel is configred to use es2015 specifically?

Thanks!

**Comment by WangShayne** [comment]
@bschulz87 🙏 thanks!

**Comment by danielgranat** [comment]
Thank you!
