### ISSUE TITLE
Not possible to trim canvas?

### ISSUE THREAD

**Issue by YatinPatel23** [WangShayne/vue-signature#42]
I am trying to trim the whitespace around the signature.  It looks like its not possible within your component but using a javascript solution returns me: 

Error in v-on handler (Promise/async): "TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'"

Is there a whitespace trimming solution for the component?

**Comment by WangShayne** [comment]
@YatinPatel23 try this ?  [https://github.com/agilgur5/trim-canvas](trim-canvas)

**Comment by YatinPatel23** [comment]
That is great thanks
