### ISSUE TITLE
Losing the signature when updating resource

### ISSUE THREAD

**Issue by ltd300** [WangShayne/vue-signature#49]
If I update resource without clicking in the "attach" button I will lose the previous data(lost signature).

Also the "saveOnChanges()" won't help unless you sign again.

I notice when updating the resource the (textarea for the signature) will give you a default value, that is a transparent background. example below. And that is the data that get saved in the DB.

What I'm looking for here is just when saving the resource keep the same signature with out clinking in the attach button.

<textarea name="signature" id="Patient Signature" style="display: none;">data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAYwAAACUCAYAAACAyx4IAAAA+klEQVR4nO3BMQEAAADCoPVPbQdvoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeA2UgQABdXK3UQAAAABJRU5ErkJggg==</textarea>

**Comment by WangShayne** [comment]
@ltd300 Can you provide a repo to let me debug

**Comment by ltd300** [comment]
Is this issue not happening to you? I mean if you update the resource without touching the signature, still show?

**Comment by WangShayne** [comment]
Okay, updating the resource like use fromDataURL? if this,the sig did not disappear,it was just overwritten.you can try set signature background to transparent,and save the sig to data,clear signature,next use fromDataURL to draw image,and draw sig again
```
    const data = _this.$refs.signature.save()
    _this.$refs.signature.clear()
    const png = require("./assets/logo.png")
    _this.$refs.signature.fromDataURL(png);
    _this.$refs.signature.fromDataURL(data)
```

**Comment by ltd300** [comment]
Can you be a little more explicit. Is this code goes in the FormField.vue?  Thank you.

**Comment by WangShayne** [comment]
```vue
<template>
  <div id="app">
    <vueSignature
      ref="signature"
      :sigOption="option"
      :w="'800px'"
      :h="'400px'"
      :disabled="disabled"
      :defaultUrl="dataUrl"
    ></vueSignature>
  </div>
</template>
<script>
import vueSignature from 'vue-signature'
export default {
  name: "app",
  components: {
    vueSignature
  },
  data() {
      return {
        option: {
          penColor: "rgb(0, 0, 0)",
          backgroundColor: "rgba(0,0,0,0)"  // set signature background to transparent
        },
        disabled: false,
        dataUrl: ""
      }
    },
  methods:{
    handleUpdate() {
        const _this = this

        // save now sig to data
        let data = _this.$refs.signature.save()

        // clear signature
        _this.$refs.signature.clear()

        // do ajax or any handle to get your image 
        let png = require("./assets/logo.png")

        // draw image
        _this.$refs.signature.fromDataURL(png)

        // overwrite your save data 
        _this.$refs.signature.fromDataURL(data)
    }
  }
 }
</script>
```

Hope to help you

**Comment by ltd300** [comment]
Thank you so much!!
