### ISSUE TITLE
2.5.4 Width / drawing breaking change with workaround

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [WangShayne/vue-signature#58]
Just updated vue-signature from 2.5.1 to 2.5.4 and my signature feature in my app broke with strange behavior on both chrome and Firefox (windows) latest releases

- Before update it rendered as a rectangle of good size in different breakpoints, after the update it rendered really tall and narrow
- After update could only get a line to draw if I dragged in the upper left corner of the vue-signature with mouse but the line it rendered was 'bloated' looking and drew all over the place in the rest of the control as if the drawing was for a much larger canvas than in place

I was previously using vue-signature directly within a v-card-text element within a dialog and it worked perfectly until the update to 2.5.4

Found a fix which works.  I needed to wrap the vue-signature within a v-sheet and to exactly specify a **matching** height and width in the parent container and the signature control props as follows:

```vue
            <v-sheet width="500px" height="250px">
              <vueSignature
                ref="sigCtrl"
                :sig-option="sigOption"
                :disabled="disabled || imgUrl != null"
                :default-url="imgUrl"
                :w="'500px'"
                :h="'250px'"
              ></vueSignature>
            </v-sheet>
```

Note that 100% in the parent sheet and nothing in the vue-signature w/h props does *not* work, nor does any other percentage based combination between the two.  Only an exact **matching** pixel width and height seem to work or the strange drawing behavior comes back.

I may well have been using it wrong in the first place but it was working perfectly so I'm not sure what changed but this seems to be a stable work around.

**Comment by cries** [comment]
I am facing the exact same issue as @WhatFreshHellIsThis since updating to the latest version 2.5.4. 
Putting a fixed size container around the signature pad was no option for me because the signature pad should expand to 100% of the width. Downgrading to 2.5.1 fixed the problem for me.
