### ISSUE TITLE
I look Error in : Cannot read property 'getContext' of null? 

### ISSUE THREAD

**Issue by fathan** [WangShayne/vue-signature#7]
i like your plugin signature for Vue.JS. but, How to solved this problem? thx

**Comment by WangShayne** [comment]
Could you provide the demo please?

**Comment by Xuryin** [comment]
i have the same problem as yours

**Comment by WangShayne** [comment]
please demo thanks

**Comment by kieranbarlow** [comment]
@fathan this will be due to the HTML not being loaded before VueJs. Simply wrap the vueSignature within a v-if statement.

For example, in your mounted.

```
mounted() {
    this.ready = true;
}
```
