### ISSUE TITLE
vue-signature doesnt work inside Vuetify v-stepper

### ISSUE THREAD

**Issue by aldarund** [WangShayne/vue-signature#8]
https://jsfiddle.net/bf85t8ng/13/

Inside v-stepper it just dont display. Outside of v-stepper all works fine.
Not entirely sure if its not a vuetify fault, but everything other work fine for me in v-stepper.
On step 2 of v-stepper i placed signature inside v-if . And if i change condition of v-if it render fine. But still dont work if initial condition is true.

**Comment by WangShayne** [comment]
Nice work! Thank you!

[fix resolve of offsetHeight and offsetWidth](https://github.com/WangShayne/vue-signature/pull/9)
